#!/bin/sh
for i in _*
do
  source="${PWD}/$i"
  target="${HOME}/${i/_/.}"
  if [ ! -L "${target}" ]
  then
    mv "${target}" "${target}.bak"
  fi
  ln -sf "${source}" "${target}"
done
git submodule sync
git submodule init
git submodule update
git submodule foreach git pull origin master
git submodule foreach git submodule init
git submodule foreach git submodule update
